server.port: 8000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/auth
    username: postgres
    password: 1111

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: test-queue
  exchange:
    name: test-exchange
  routing:
    key: key