server.port: 8001

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8000/auth
    username: postgres
    password: 1111

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true

  rabbitmq:
    host: localhost
    port: 3000
    username: guest
    password: guest

rabbitmq:
  queue:
    name: test-queue
  exchange:
    name: test-exchange
  routing:
    key: key