server.port: 8001

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://61.109.238.66:8000/auth
    username: postgres
    password: 1111

  rabbitmq:
    host: 61.109.238.66
    port: 3000
    username: guest
    password: guest

rabbitmq:
  queue:
    name: test-queue
  exchange:
    name: test-exchange
  routing:
    key: key